FROM rust:1.87.0-slim-bookworm AS builder
WORKDIR /usr/src/app
RUN apt-get update && \
    apt-get install -y --no-install-recommends npm && \
    rm -rf /var/lib/apt/lists/*
RUN cargo install trunk wasm-bindgen-cli
COPY . .
RUN trunk build --release

FROM nginx:1.25-alpine
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
