services:
  app:
    build: .
    image: rust-regex-gui:latest
    container_name: regex-gui
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: rust-regex-gui-web:latest
    container_name: regex-gui-web
    ports:
      - "8080:80"
