name: '[Workflow] On PR Synchronize'

concurrency:
  group: pr-sync-${{ github.event.pull_request.head.ref || github.event.pull_request.base.ref }}

on:
  pull_request:
    types: [synchronize]
    branches:
      - '*'

jobs:
  static-analysis:
    name: 'Static Analysis'
    uses: webgrip/workflows/.github/workflows/rust-static-analysis.yml@ubuntu-latest

  tests:
    name: 'Tests'
    uses: webgrip/workflows/.github/workflows/rust-tests.yml@ubuntu-latest

  semantic-release:
    name: 'Semantic Release'
    needs: [ static-analysis, tests ]
    if: always() && needs.tests.result == 'success' && github.ref == 'refs/heads/main'
    uses: webgrip/workflows/.github/workflows/rust-semantic-release.yml@ubuntu-latest

  # build-docker-image:
  #   name: 'Build Docker Image'
  #   needs: [ static-analysis, tests ]
  #   if: always() && needs.tests.result == 'success'
  #   uses: webgrip/workflows/.github/workflows/rust-build-docker-image.yml@ubuntu-latest

