name: '[Workflow] On Source Change'

concurrency:
  group: push-${{ github.branch }}

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/on_source_change.yml'
      - '.releaserc.json'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  static-analysis:
    name: 'Static Analysis'
    uses: webgrip/workflows/.github/workflows/rust-static-analysis.yml@main

  tests:
    name: 'Tests'
    uses: webgrip/workflows/.github/workflows/rust-tests.yml@main

  semantic-release:
    name: 'Semantic Release'
    needs: [ static-analysis, tests ]
    if: always() && needs.tests.result == 'success' && github.ref == 'refs/heads/main'
    uses: webgrip/workflows/.github/workflows/rust-semantic-release.yml@main

  # build-docker-image:
  #   name: 'Build Docker Image'
  #   needs: [ static-analysis, tests ]
  #   if: always() && needs.tests.result == 'success'
  #   uses: webgrip/workflows/.github/workflows/rust-build-docker-image.yml@main

